services:
  mysqldb:
    image: mysql:latest
    container_name: db_composer
    networks:
      - net
    ports:
      - "3306:3306"
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  app:
    build: .
    container_name: app_sorteo
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - net
    ports:
      - "3000:3000"
    env_file:
      - .env

networks:
  net:







