name: CInp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ajusta según tu versión estable preferida

      - name: Change directory to backend
        working-directory: ./backend
        run: pwd  # Para verificar en qué directorio estamos

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Fix permissions for Mocha
        working-directory: ./backend
        run: chmod +x ./node_modules/.bin/mocha
      
      - name: Run tests
        working-directory: ./backend
        run: npm test





